all:
		xrun -access +rwc -sv -linedebug \
				     -input "run.tcl" \
						 	     -f listfile.f

wave:
		xrun -access +rwc -sv -linedebug \
				     -input "wave.tcl" \
						 	     -gui -f listfile.f &

